// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: grieflogger_queries.sql

package repo

import (
	"context"
)

const findGriefLoggerFirstJoinByUser = `-- name: FindGriefLoggerFirstJoinByUser :one
SELECT
  time, user, level, x, y, z, action
FROM
  sessions
WHERE
  user = ?
ORDER BY
  time
ASC
LIMIT 1
`

func (q *Queries) FindGriefLoggerFirstJoinByUser(ctx context.Context, user int32) (Session, error) {
	row := q.db.QueryRowContext(ctx, findGriefLoggerFirstJoinByUser, user)
	var i Session
	err := row.Scan(
		&i.Time,
		&i.User,
		&i.Level,
		&i.X,
		&i.Y,
		&i.Z,
		&i.Action,
	)
	return i, err
}

const findGriefLoggerUserByUuid = `-- name: FindGriefLoggerUserByUuid :one
SELECT
  id, name, uuid
FROM
  users
WHERE
  uuid = ?
`

func (q *Queries) FindGriefLoggerUserByUuid(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, findGriefLoggerUserByUuid, uuid)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Uuid)
	return i, err
}

const groupCountBlocksPlacedByUser = `-- name: GroupCountBlocksPlacedByUser :many
SELECT
  type, COUNT(*) AS total_placed
FROM
  blocks
WHERE
  user = ?
AND
  action = 1
GROUP BY
  type
`

type GroupCountBlocksPlacedByUserRow struct {
	Type        int32 `json:"type"`
	TotalPlaced int64 `json:"total_placed"`
}

func (q *Queries) GroupCountBlocksPlacedByUser(ctx context.Context, user int32) ([]GroupCountBlocksPlacedByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, groupCountBlocksPlacedByUser, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupCountBlocksPlacedByUserRow
	for rows.Next() {
		var i GroupCountBlocksPlacedByUserRow
		if err := rows.Scan(&i.Type, &i.TotalPlaced); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksBrokenByUser = `-- name: ListBlocksBrokenByUser :many
SELECT
  time, user, level, x, y, z, type, action
FROM
  blocks
WHERE
  user = ?
AND
  action = 0
`

func (q *Queries) ListBlocksBrokenByUser(ctx context.Context, user int32) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, listBlocksBrokenByUser, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.Time,
			&i.User,
			&i.Level,
			&i.X,
			&i.Y,
			&i.Z,
			&i.Type,
			&i.Action,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocksPlacedByUser = `-- name: ListBlocksPlacedByUser :many
SELECT
  time, user, level, x, y, z, type, action
FROM
  blocks
WHERE
  user = ?
AND
  action = 1
`

func (q *Queries) ListBlocksPlacedByUser(ctx context.Context, user int32) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, listBlocksPlacedByUser, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.Time,
			&i.User,
			&i.Level,
			&i.X,
			&i.Y,
			&i.Z,
			&i.Type,
			&i.Action,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGriefLoggerSessionsByUser = `-- name: ListGriefLoggerSessionsByUser :many
SELECT
  time, user, level, x, y, z, action
FROM
  sessions
WHERE
  user = ?
`

func (q *Queries) ListGriefLoggerSessionsByUser(ctx context.Context, user int32) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listGriefLoggerSessionsByUser, user)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.Time,
			&i.User,
			&i.Level,
			&i.X,
			&i.Y,
			&i.Z,
			&i.Action,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterials = `-- name: ListMaterials :many
SELECT
  id, name
FROM
  materials
`

func (q *Queries) ListMaterials(ctx context.Context) ([]Material, error) {
	rows, err := q.db.QueryContext(ctx, listMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
