// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_queries.sql

package repo

import (
	"context"
)

const findLedgerPlayerByUuid = `-- name: FindLedgerPlayerByUuid :one
SELECT
  id, player_id, player_name, first_join, last_join
FROM 
  players
WHERE
  player_id = ?
`

func (q *Queries) FindLedgerPlayerByUuid(ctx context.Context, playerID []byte) (Player, error) {
	row := q.db.QueryRowContext(ctx, findLedgerPlayerByUuid, playerID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.PlayerName,
		&i.FirstJoin,
		&i.LastJoin,
	)
	return i, err
}

const listActions = `-- name: ListActions :many
SELECT
  id, action_id, time, x, y, z, world_id, object_id, old_object_id, block_state, old_block_state, source, player_id, extra_data, rolled_back
FROM
  actions
`

func (q *Queries) ListActions(ctx context.Context) ([]Action, error) {
	rows, err := q.db.QueryContext(ctx, listActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Time,
			&i.X,
			&i.Y,
			&i.Z,
			&i.WorldID,
			&i.ObjectID,
			&i.OldObjectID,
			&i.BlockState,
			&i.OldBlockState,
			&i.Source,
			&i.PlayerID,
			&i.ExtraData,
			&i.RolledBack,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionsIdentifiers = `-- name: ListActionsIdentifiers :many
SELECT
  id, action_identifier
FROM
  ActionIdentifiers
`

func (q *Queries) ListActionsIdentifiers(ctx context.Context) ([]Actionidentifier, error) {
	rows, err := q.db.QueryContext(ctx, listActionsIdentifiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Actionidentifier
	for rows.Next() {
		var i Actionidentifier
		if err := rows.Scan(&i.ID, &i.ActionIdentifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerPlayers = `-- name: ListLedgerPlayers :many
SELECT
  id, player_id, player_name, first_join, last_join
FROM
  players
`

func (q *Queries) ListLedgerPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.PlayerName,
			&i.FirstJoin,
			&i.LastJoin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjects = `-- name: ListObjects :many
SELECT
  id, identifier
FROM
  ObjectIdentifiers
`

func (q *Queries) ListObjects(ctx context.Context) ([]Objectidentifier, error) {
	rows, err := q.db.QueryContext(ctx, listObjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Objectidentifier
	for rows.Next() {
		var i Objectidentifier
		if err := rows.Scan(&i.ID, &i.Identifier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
