// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: luckperms_queries.sql

package repo

import (
	"context"
)

const findLuckpermsPlayerByUuid = `-- name: FindLuckpermsPlayerByUuid :one
SELECT
  uuid, username, primary_group
FROM
  luckperms_players
WHERE
  uuid = ?
`

func (q *Queries) FindLuckpermsPlayerByUuid(ctx context.Context, uuid string) (LuckpermsPlayer, error) {
	row := q.db.QueryRowContext(ctx, findLuckpermsPlayerByUuid, uuid)
	var i LuckpermsPlayer
	err := row.Scan(&i.Uuid, &i.Username, &i.PrimaryGroup)
	return i, err
}

const listLuckpermsPlayers = `-- name: ListLuckpermsPlayers :many
SELECT
  uuid, username, primary_group
FROM
  luckperms_players
`

func (q *Queries) ListLuckpermsPlayers(ctx context.Context) ([]LuckpermsPlayer, error) {
	rows, err := q.db.QueryContext(ctx, listLuckpermsPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LuckpermsPlayer
	for rows.Next() {
		var i LuckpermsPlayer
		if err := rows.Scan(&i.Uuid, &i.Username, &i.PrimaryGroup); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
