// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

type Block struct {
	Time   int64 `json:"time"`
	User   int32 `json:"user"`
	Level  int32 `json:"level"`
	X      int32 `json:"x"`
	Y      int32 `json:"y"`
	Z      int32 `json:"z"`
	Type   int32 `json:"type"`
	Action int32 `json:"action"`
}

type LuckpermsPlayer struct {
	Uuid         string `json:"uuid"`
	Username     string `json:"username"`
	PrimaryGroup string `json:"primary_group"`
}

type Material struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type PsmpstatsAdvancement struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type PsmpstatsCause struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type PsmpstatsCombat struct {
	PlayerID int32  `json:"player_id"`
	VictimID int32  `json:"victim_id"`
	Time     int32  `json:"time"`
	World    string `json:"world"`
	X        int32  `json:"x"`
	Y        int32  `json:"y"`
	Z        int32  `json:"z"`
}

type PsmpstatsDeath struct {
	PlayerID int32  `json:"player_id"`
	Time     int32  `json:"time"`
	World    string `json:"world"`
	X        int32  `json:"x"`
	Y        int32  `json:"y"`
	Z        int32  `json:"z"`
	Cause    int32  `json:"cause"`
}

type PsmpstatsDiamondsMined struct {
	PlayerID int32 `json:"player_id"`
	Time     int32 `json:"time"`
}

type PsmpstatsMob struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type PsmpstatsMobKill struct {
	PlayerID int32  `json:"player_id"`
	Time     int32  `json:"time"`
	World    string `json:"world"`
	X        int32  `json:"x"`
	Y        int32  `json:"y"`
	Z        int32  `json:"z"`
	Mob      int32  `json:"mob"`
}

type PsmpstatsPlayer struct {
	ID   int32  `json:"id"`
	Uuid string `json:"uuid"`
}

type PsmpstatsPlayerAdvancement struct {
	PlayerID    int32 `json:"player_id"`
	Time        int32 `json:"time"`
	Advancement int32 `json:"advancement"`
}

type Session struct {
	Time   int64 `json:"time"`
	User   int32 `json:"user"`
	Level  int32 `json:"level"`
	X      int32 `json:"x"`
	Y      int32 `json:"y"`
	Z      int32 `json:"z"`
	Action int32 `json:"action"`
}

type User struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Uuid string `json:"uuid"`
}
