// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql"
	"time"
)

type Action struct {
	ID            int32          `json:"id"`
	ActionID      int32          `json:"action_id"`
	Time          time.Time      `json:"time"`
	X             int32          `json:"x"`
	Y             int32          `json:"y"`
	Z             int32          `json:"z"`
	WorldID       int32          `json:"world_id"`
	ObjectID      int32          `json:"object_id"`
	OldObjectID   int32          `json:"old_object_id"`
	BlockState    sql.NullString `json:"block_state"`
	OldBlockState sql.NullString `json:"old_block_state"`
	Source        int32          `json:"source"`
	PlayerID      sql.NullInt32  `json:"player_id"`
	ExtraData     sql.NullString `json:"extra_data"`
	RolledBack    bool           `json:"rolled_back"`
}

type Actionidentifier struct {
	ID               int32  `json:"id"`
	ActionIdentifier string `json:"action_identifier"`
}

type Block struct {
	Time   int64 `json:"time"`
	User   int32 `json:"user"`
	Level  int32 `json:"level"`
	X      int32 `json:"x"`
	Y      int32 `json:"y"`
	Z      int32 `json:"z"`
	Type   int32 `json:"type"`
	Action int32 `json:"action"`
}

type LuckpermsPlayer struct {
	Uuid         string `json:"uuid"`
	Username     string `json:"username"`
	PrimaryGroup string `json:"primary_group"`
}

type Material struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Objectidentifier struct {
	ID         int32  `json:"id"`
	Identifier string `json:"identifier"`
}

type Player struct {
	ID         int32     `json:"id"`
	PlayerID   []byte    `json:"player_id"`
	PlayerName string    `json:"player_name"`
	FirstJoin  time.Time `json:"first_join"`
	LastJoin   time.Time `json:"last_join"`
}

type PsmpstatsAdvancement struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type PsmpstatsCause struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type PsmpstatsCombat struct {
	PlayerID int32  `json:"player_id"`
	VictimID int32  `json:"victim_id"`
	Time     int32  `json:"time"`
	World    string `json:"world"`
	X        int32  `json:"x"`
	Y        int32  `json:"y"`
	Z        int32  `json:"z"`
}

type PsmpstatsDeath struct {
	PlayerID int32  `json:"player_id"`
	Time     int32  `json:"time"`
	World    string `json:"world"`
	X        int32  `json:"x"`
	Y        int32  `json:"y"`
	Z        int32  `json:"z"`
	Cause    int32  `json:"cause"`
}

type PsmpstatsDiamondsMined struct {
	PlayerID int32 `json:"player_id"`
	Time     int32 `json:"time"`
}

type PsmpstatsFish struct {
	PlayerID int32  `json:"player_id"`
	Time     int32  `json:"time"`
	Fish     string `json:"fish"`
	Size     int32  `json:"size"`
}

type PsmpstatsMob struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type PsmpstatsMobKill struct {
	PlayerID int32  `json:"player_id"`
	Time     int32  `json:"time"`
	World    string `json:"world"`
	X        int32  `json:"x"`
	Y        int32  `json:"y"`
	Z        int32  `json:"z"`
	Mob      int32  `json:"mob"`
}

type PsmpstatsPlayer struct {
	ID   int32  `json:"id"`
	Uuid string `json:"uuid"`
}

type PsmpstatsPlayerAdvancement struct {
	PlayerID    int32 `json:"player_id"`
	Time        int32 `json:"time"`
	Advancement int32 `json:"advancement"`
}

type PsmpstatsSession struct {
	PlayerID int32 `json:"player_id"`
	Time     int32 `json:"time"`
	Action   int32 `json:"action"`
}

type Session struct {
	Time   int64 `json:"time"`
	User   int32 `json:"user"`
	Level  int32 `json:"level"`
	X      int32 `json:"x"`
	Y      int32 `json:"y"`
	Z      int32 `json:"z"`
	Action int32 `json:"action"`
}

type Source struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Uuid string `json:"uuid"`
}
