// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

type Block struct {
	Time   int64 `json:"time"`
	User   int32 `json:"user"`
	Level  int32 `json:"level"`
	X      int32 `json:"x"`
	Y      int32 `json:"y"`
	Z      int32 `json:"z"`
	Type   int32 `json:"type"`
	Action int32 `json:"action"`
}

type LuckpermsPlayer struct {
	Uuid         string `json:"uuid"`
	Username     string `json:"username"`
	PrimaryGroup string `json:"primary_group"`
}

type Material struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Uuid string `json:"uuid"`
}
