// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: psmpstats_queries.sql

package repo

import (
	"context"
	"database/sql"
)

const countDeathsById = `-- name: CountDeathsById :one
SELECT
  count(*)
FROM
  psmpstats_deaths
WHERE
  player_id = ?
`

func (q *Queries) CountDeathsById(ctx context.Context, playerID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeathsById, playerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMobsKilledById = `-- name: CountMobsKilledById :one
SELECT
  count(*)
FROM
  psmpstats_mob_kills
WHERE
  player_id = ?
`

func (q *Queries) CountMobsKilledById(ctx context.Context, playerID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMobsKilledById, playerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPvpKillsById = `-- name: CountPvpKillsById :one
SELECT
  count(*)
FROM
  psmpstats_combat
WHERE
  player_id = ?
`

func (q *Queries) CountPvpKillsById(ctx context.Context, playerID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPvpKillsById, playerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpecificMobKillsById = `-- name: CountSpecificMobKillsById :one
SELECT
  count(*)
FROM
  psmpstats_mob_kills
WHERE
  player_id = ?
AND
  mob = (
    SELECT
      id
    FROM
      psmpstats_mobs
    WHERE
      name = ?
  )
`

type CountSpecificMobKillsByIdParams struct {
	PlayerID int32  `json:"player_id"`
	Name     string `json:"name"`
}

func (q *Queries) CountSpecificMobKillsById(ctx context.Context, arg CountSpecificMobKillsByIdParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpecificMobKillsById, arg.PlayerID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findPsmpstatsPlayerByUuid = `-- name: FindPsmpstatsPlayerByUuid :one
SELECT
  id, uuid
FROM
  psmpstats_players
WHERE
  uuid = ?
`

func (q *Queries) FindPsmpstatsPlayerByUuid(ctx context.Context, uuid string) (PsmpstatsPlayer, error) {
	row := q.db.QueryRowContext(ctx, findPsmpstatsPlayerByUuid, uuid)
	var i PsmpstatsPlayer
	err := row.Scan(&i.ID, &i.Uuid)
	return i, err
}

const listAdvancements = `-- name: ListAdvancements :many
SELECT
  id, name
FROM
  psmpstats_advancements
`

func (q *Queries) ListAdvancements(ctx context.Context) ([]PsmpstatsAdvancement, error) {
	rows, err := q.db.QueryContext(ctx, listAdvancements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsAdvancement
	for rows.Next() {
		var i PsmpstatsAdvancement
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdvancementsById = `-- name: ListAdvancementsById :many
SELECT
  id, name, player_id, time, advancement
FROM
  psmpstats_advancements
LEFT JOIN
  psmpstats_player_advancements
ON
  psmpstats_advancements.id = psmpstats_player_advancements.advancement
WHERE
  psmpstats_player_advancements.player_id = ?
`

type ListAdvancementsByIdRow struct {
	ID          uint64        `json:"id"`
	Name        string        `json:"name"`
	PlayerID    sql.NullInt32 `json:"player_id"`
	Time        sql.NullInt32 `json:"time"`
	Advancement sql.NullInt32 `json:"advancement"`
}

func (q *Queries) ListAdvancementsById(ctx context.Context, playerID int32) ([]ListAdvancementsByIdRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdvancementsById, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdvancementsByIdRow
	for rows.Next() {
		var i ListAdvancementsByIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PlayerID,
			&i.Time,
			&i.Advancement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCausesOfDeath = `-- name: ListCausesOfDeath :many
SELECT
  id, name
FROM
  psmpstats_causes
`

func (q *Queries) ListCausesOfDeath(ctx context.Context) ([]PsmpstatsCause, error) {
	rows, err := q.db.QueryContext(ctx, listCausesOfDeath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsCause
	for rows.Next() {
		var i PsmpstatsCause
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeathsById = `-- name: ListDeathsById :many
SELECT
  player_id, time, world, x, y, z, cause
FROM
  psmpstats_deaths
WHERE
  player_id = ?
`

func (q *Queries) ListDeathsById(ctx context.Context, playerID int32) ([]PsmpstatsDeath, error) {
	rows, err := q.db.QueryContext(ctx, listDeathsById, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsDeath
	for rows.Next() {
		var i PsmpstatsDeath
		if err := rows.Scan(
			&i.PlayerID,
			&i.Time,
			&i.World,
			&i.X,
			&i.Y,
			&i.Z,
			&i.Cause,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMobKillsById = `-- name: ListMobKillsById :many
SELECT
  player_id, time, world, x, y, z, mob
FROM
  psmpstats_mob_kills
WHERE
  player_id = ?
`

func (q *Queries) ListMobKillsById(ctx context.Context, playerID int32) ([]PsmpstatsMobKill, error) {
	rows, err := q.db.QueryContext(ctx, listMobKillsById, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsMobKill
	for rows.Next() {
		var i PsmpstatsMobKill
		if err := rows.Scan(
			&i.PlayerID,
			&i.Time,
			&i.World,
			&i.X,
			&i.Y,
			&i.Z,
			&i.Mob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMobs = `-- name: ListMobs :many
SELECT
  id, name
FROM
  psmpstats_mobs
`

func (q *Queries) ListMobs(ctx context.Context) ([]PsmpstatsMob, error) {
	rows, err := q.db.QueryContext(ctx, listMobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsMob
	for rows.Next() {
		var i PsmpstatsMob
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerAdvancementsById = `-- name: ListPlayerAdvancementsById :many
SELECT
  player_id, time, advancement
FROM
  psmpstats_player_advancements
WHERE
  player_id = ?
`

func (q *Queries) ListPlayerAdvancementsById(ctx context.Context, playerID int32) ([]PsmpstatsPlayerAdvancement, error) {
	rows, err := q.db.QueryContext(ctx, listPlayerAdvancementsById, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsPlayerAdvancement
	for rows.Next() {
		var i PsmpstatsPlayerAdvancement
		if err := rows.Scan(&i.PlayerID, &i.Time, &i.Advancement); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPvpKillsById = `-- name: ListPvpKillsById :many
SELECT
 player_id, victim_id, time, world, x, y, z
FROM
  psmpstats_combat
WHERE
  player_id = ?
`

func (q *Queries) ListPvpKillsById(ctx context.Context, playerID int32) ([]PsmpstatsCombat, error) {
	rows, err := q.db.QueryContext(ctx, listPvpKillsById, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsCombat
	for rows.Next() {
		var i PsmpstatsCombat
		if err := rows.Scan(
			&i.PlayerID,
			&i.VictimID,
			&i.Time,
			&i.World,
			&i.X,
			&i.Y,
			&i.Z,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
