// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: psmpstats_queries.sql

package repo

import (
	"context"
	"database/sql"
)

const countDeathsByUuid = `-- name: CountDeathsByUuid :one
SELECT
  count(*)
FROM
  psmpstats_deaths
WHERE
  player_uuid = ?
`

func (q *Queries) CountDeathsByUuid(ctx context.Context, playerUuid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeathsByUuid, playerUuid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMobsKilledByUUid = `-- name: CountMobsKilledByUUid :one
SELECT
  count(*)
FROM
  psmpstats_mob_kills
WHERE
  player_uuid = ?
`

func (q *Queries) CountMobsKilledByUUid(ctx context.Context, playerUuid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMobsKilledByUUid, playerUuid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPvpKillsByUuid = `-- name: CountPvpKillsByUuid :one
SELECT
  count(*)
FROM
  psmpstats_combat
WHERE
  player_uuid = ?
`

func (q *Queries) CountPvpKillsByUuid(ctx context.Context, playerUuid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPvpKillsByUuid, playerUuid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpecificMobKillsByUuid = `-- name: CountSpecificMobKillsByUuid :one
SELECT
  count(*)
FROM
  psmpstats_mob_kills
WHERE
  player_uuid = ?
AND
  mob = ?
`

type CountSpecificMobKillsByUuidParams struct {
	PlayerUuid string `json:"player_uuid"`
	Mob        int32  `json:"mob"`
}

func (q *Queries) CountSpecificMobKillsByUuid(ctx context.Context, arg CountSpecificMobKillsByUuidParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpecificMobKillsByUuid, arg.PlayerUuid, arg.Mob)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findPsmpstatsPlayerByUuid = `-- name: FindPsmpstatsPlayerByUuid :one
SELECT
  uuid, diamonds_mined
FROM
  psmpstats_players
WHERE
  uuid = ?
`

func (q *Queries) FindPsmpstatsPlayerByUuid(ctx context.Context, uuid string) (PsmpstatsPlayer, error) {
	row := q.db.QueryRowContext(ctx, findPsmpstatsPlayerByUuid, uuid)
	var i PsmpstatsPlayer
	err := row.Scan(&i.Uuid, &i.DiamondsMined)
	return i, err
}

const listAdvancements = `-- name: ListAdvancements :many
SELECT
  id, name
FROM
  psmpstats_advancements
`

func (q *Queries) ListAdvancements(ctx context.Context) ([]PsmpstatsAdvancement, error) {
	rows, err := q.db.QueryContext(ctx, listAdvancements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsAdvancement
	for rows.Next() {
		var i PsmpstatsAdvancement
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdvancementsByUuid = `-- name: ListAdvancementsByUuid :many
SELECT
  player_uuid, time, advancement
FROM
  psmpstats_player_advancements
WHERE
  player_uuid = ?
`

func (q *Queries) ListAdvancementsByUuid(ctx context.Context, playerUuid sql.NullString) ([]PsmpstatsPlayerAdvancement, error) {
	rows, err := q.db.QueryContext(ctx, listAdvancementsByUuid, playerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsPlayerAdvancement
	for rows.Next() {
		var i PsmpstatsPlayerAdvancement
		if err := rows.Scan(&i.PlayerUuid, &i.Time, &i.Advancement); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCausesOfDeath = `-- name: ListCausesOfDeath :many
SELECT
  id, name
FROM
  psmpstats_causes
`

func (q *Queries) ListCausesOfDeath(ctx context.Context) ([]PsmpstatsCause, error) {
	rows, err := q.db.QueryContext(ctx, listCausesOfDeath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsCause
	for rows.Next() {
		var i PsmpstatsCause
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeathsByUuid = `-- name: ListDeathsByUuid :many
SELECT
  player_uuid, time, world, x, y, z, cause
FROM
  psmpstats_deaths
WHERE
  player_uuid = ?
`

func (q *Queries) ListDeathsByUuid(ctx context.Context, playerUuid string) ([]PsmpstatsDeath, error) {
	rows, err := q.db.QueryContext(ctx, listDeathsByUuid, playerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsDeath
	for rows.Next() {
		var i PsmpstatsDeath
		if err := rows.Scan(
			&i.PlayerUuid,
			&i.Time,
			&i.World,
			&i.X,
			&i.Y,
			&i.Z,
			&i.Cause,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMobKillsByUuid = `-- name: ListMobKillsByUuid :many
SELECT
  player_uuid, time, world, x, y, z, mob
FROM
  psmpstats_mob_kills
WHERE
  player_uuid = ?
`

func (q *Queries) ListMobKillsByUuid(ctx context.Context, playerUuid string) ([]PsmpstatsMobKill, error) {
	rows, err := q.db.QueryContext(ctx, listMobKillsByUuid, playerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsMobKill
	for rows.Next() {
		var i PsmpstatsMobKill
		if err := rows.Scan(
			&i.PlayerUuid,
			&i.Time,
			&i.World,
			&i.X,
			&i.Y,
			&i.Z,
			&i.Mob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMobs = `-- name: ListMobs :many
SELECT
  id, name
FROM
  psmpstats_mobs
`

func (q *Queries) ListMobs(ctx context.Context) ([]PsmpstatsMob, error) {
	rows, err := q.db.QueryContext(ctx, listMobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsMob
	for rows.Next() {
		var i PsmpstatsMob
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPvpKillsByUuid = `-- name: ListPvpKillsByUuid :many
SELECT
 player_uuid, victim_uuid, time, world, x, y, z
FROM
  psmpstats_combat
WHERE
  player_uuid = ?
`

func (q *Queries) ListPvpKillsByUuid(ctx context.Context, playerUuid string) ([]PsmpstatsCombat, error) {
	rows, err := q.db.QueryContext(ctx, listPvpKillsByUuid, playerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PsmpstatsCombat
	for rows.Next() {
		var i PsmpstatsCombat
		if err := rows.Scan(
			&i.PlayerUuid,
			&i.VictimUuid,
			&i.Time,
			&i.World,
			&i.X,
			&i.Y,
			&i.Z,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
