// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CountDeathsById(ctx context.Context, playerID int32) (int64, error)
	CountDiamondsMinedById(ctx context.Context, playerID int32) (int64, error)
	CountMobsKilledById(ctx context.Context, playerID int32) (int64, error)
	CountPvpKillsById(ctx context.Context, playerID int32) (int64, error)
	CountSpecificMobKillsById(ctx context.Context, arg CountSpecificMobKillsByIdParams) (int64, error)
	FindFirstJoinByUser(ctx context.Context, user int32) (Session, error)
	FindGriefLoggerUserByUuid(ctx context.Context, uuid string) (User, error)
	FindLuckpermsPlayerByUuid(ctx context.Context, uuid string) (LuckpermsPlayer, error)
	FindPsmpstatsPlayerByUuid(ctx context.Context, uuid string) (PsmpstatsPlayer, error)
	GroupCountBlocksPlacedByUser(ctx context.Context, user int32) ([]GroupCountBlocksPlacedByUserRow, error)
	ListAdvancements(ctx context.Context) ([]PsmpstatsAdvancement, error)
	ListAdvancementsById(ctx context.Context, playerID int32) ([]ListAdvancementsByIdRow, error)
	ListBlocksBrokenByUser(ctx context.Context, user int32) ([]Block, error)
	ListBlocksPlacedByUser(ctx context.Context, user int32) ([]Block, error)
	ListCausesOfDeath(ctx context.Context) ([]PsmpstatsCause, error)
	ListDeathsById(ctx context.Context, playerID int32) ([]PsmpstatsDeath, error)
	ListDiamondsMinedById(ctx context.Context, playerID int32) ([]PsmpstatsDiamondsMined, error)
	ListLuckpermsPlayers(ctx context.Context) ([]LuckpermsPlayer, error)
	ListMaterials(ctx context.Context) ([]Material, error)
	ListMobKillsById(ctx context.Context, playerID int32) ([]PsmpstatsMobKill, error)
	ListMobs(ctx context.Context) ([]PsmpstatsMob, error)
	ListPlayerAdvancementsById(ctx context.Context, playerID int32) ([]PsmpstatsPlayerAdvancement, error)
	ListPvpKillsById(ctx context.Context, playerID int32) ([]PsmpstatsCombat, error)
	ListSessionDataByUser(ctx context.Context, user int32) ([]Session, error)

	//dynamic queries
	CountBlocksByUser(ctx context.Context, user int32, action int32, banned []int32) (int64, error)
	GroupCountBlocksByUser(ctx context.Context, user int32, action int32, banned []int32) ([]GroupCountBlocksPlacedByUserRow, error)
	ListBlocksByUser(ctx context.Context, user int32, action int32, banned []int32) ([]Block, error)
}

var _ Querier = (*Queries)(nil)
