// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CountDeathsById(ctx context.Context, playerID int32) (int64, error)
	CountDiamondsMinedById(ctx context.Context, playerID int32) (int64, error)
	CountFishCaughtByPlayer(ctx context.Context, playerID int32) (int64, error)
	CountMobsKilledById(ctx context.Context, playerID int32) (int64, error)
	CountPvpKillsById(ctx context.Context, playerID int32) (int64, error)
	CountSpecificMobKillsById(ctx context.Context, arg CountSpecificMobKillsByIdParams) (int64, error)
	FindGriefLoggerFirstJoinByUser(ctx context.Context, user int32) (Session, error)
	FindGriefLoggerUserByUuid(ctx context.Context, uuid string) (User, error)
	FindLedgerPlayerByUuid(ctx context.Context, playerID []byte) (Player, error)
	FindLuckpermsPlayerByUuid(ctx context.Context, uuid string) (LuckpermsPlayer, error)
	FindPsmpstatsFirstJoinById(ctx context.Context, playerID int32) (PsmpstatsSession, error)
	FindPsmpstatsPlayerByUuid(ctx context.Context, uuid string) (PsmpstatsPlayer, error)
	GroupCountBlocksPlacedByUser(ctx context.Context, user int32) ([]GroupCountBlocksPlacedByUserRow, error)
	GroupCountMobKillsByPlayer(ctx context.Context, playerID int32) ([]GroupCountMobKillsByPlayerRow, error)
	ListActions(ctx context.Context) ([]Action, error)
	ListActionsIdentifiers(ctx context.Context) ([]Actionidentifier, error)
	ListAdvancements(ctx context.Context) ([]PsmpstatsAdvancement, error)
	ListAdvancementsById(ctx context.Context, playerID int32) ([]ListAdvancementsByIdRow, error)
	ListBlocksBrokenByUser(ctx context.Context, user int32) ([]Block, error)
	ListBlocksPlacedByUser(ctx context.Context, user int32) ([]Block, error)
	ListCausesOfDeath(ctx context.Context) ([]PsmpstatsCause, error)
	ListDeathsById(ctx context.Context, playerID int32) ([]PsmpstatsDeath, error)
	ListDiamondsMinedById(ctx context.Context, playerID int32) ([]PsmpstatsDiamondsMined, error)
	ListGriefLoggerSessionsByUser(ctx context.Context, user int32) ([]Session, error)
	ListLedgerPlayers(ctx context.Context) ([]Player, error)
	ListLuckpermsPlayers(ctx context.Context) ([]LuckpermsPlayer, error)
	ListMaterials(ctx context.Context) ([]Material, error)
	ListMobKillsById(ctx context.Context, playerID int32) ([]PsmpstatsMobKill, error)
	ListMobs(ctx context.Context) ([]PsmpstatsMob, error)
	ListObjects(ctx context.Context) ([]Objectidentifier, error)
	ListPlayerAdvancementsById(ctx context.Context, playerID int32) ([]PsmpstatsPlayerAdvancement, error)
	ListPsmpstatsSessionsById(ctx context.Context, playerID int32) ([]PsmpstatsSession, error)
	ListPvpKillsById(ctx context.Context, playerID int32) ([]PsmpstatsCombat, error)

	//dynamic queries
	GriefLoggerCountBlocksByUser(ctx context.Context, user int32, action int32, banned []int32) (int64, error)
	LedgerCountBlocksByUser(ctx context.Context, actions map[string]int32, user int32, action int32, banned []int32) (int64, error)
	GriefLoggerGroupCountBlocksByUser(ctx context.Context, user int32, action int32, banned []int32) ([]GroupCountBlocksPlacedByUserRow, error)
	LedgerGroupCountBlocksByUser(ctx context.Context, actions map[string]int32, user int32, action int32, banned []int32) ([]GroupCountBlocksPlacedByUserRow, error)
	GriefLoggerListBlocksByUser(ctx context.Context, user int32, action int32, banned []int32) ([]Block, error)
	LedgerListBlocksByUser(ctx context.Context, actions map[string]int32, user int32, action int32, banned []int32) ([]Action, error)
}

var _ Querier = (*Queries)(nil)
