package mapping

const BLOCK_BROKEN_ACTION = 0
const BLOCK_PLACED_ACTION = 1
const PLAYER_JOIN_ACTION = 0
const PLAYER_LEAVE_ACTION = 1

const ELDER_GUARDIAN = "elder_guardian"
const ENDER_DRAGON = "ender_dragon"
const EVOKER = "evoker"
const PIGLIN_BRUTE = "piglin_brute"
const WARDEN = "warden"
const WITHER = "wither"

var BANNED_PLACED_MATERIALS = []string{
	"minecraft:short_grass",
	"minecraft:tall_grass",
	"minecraft:fire",
	"minecraft:large_fern",
	"minecraft:seagrass",
	"minecraft:shulker_box",
	"minecraft:allium",
	"minecraft:azure_bluet",
	"minecraft:red_tulip",
	"minecraft:orange_tulip",
	"minecraft:white_tulip",
	"minecraft:lily_of_the_valley",
	"minecraft:wildflowers",
	"minecraft:pink_petals",
	"minecraft:peony",
	"minecraft:rose_bush",
	"minecraft:lilac",
	"minecraft:moss_carpet",
	"minecraft:sculk_vein",
	"minecraft:dandelion",
	"minecraft:sunflower",
	"minecraft:oxeye_daisy",
	"minecraft:poppy",
	"minecraft:cornflower",
	"minecraft:pink_tulip",
	"minecraft:blue_orchid",
	"minecraft:leaf_litter",
}

var BANNED_BROKEN_MATERIALS = []string{
	"minecraft:netherrack",
	"minecraft:short_grass",
	"minecraft:tall_grass",
	"minecraft:fire",
	"minecraft:oak_leaves",
	"minecraft:fern",
	"minecraft:large_fern",
	"minecraft:birch_leaves",
	"minecraft:spruce_leaves",
	"minecraft:seagrass",
	"minecraft:flowering_azalea_leaves",
	"minecraft:dark_oak_leaves",
	"minecraft:cherry_leaves",
	"minecraft:soul_soil",
	"minecraft:soul_sand",
	"minecraft:jungle_leaves",
	"minecraft:azalea_leaves",
	"minecraft:mangrove_leaves",
	"minecraft:pale_oak_leaves",
	"minecraft:dead_bush",
	"minecraft:shulker_box",
	"minecraft:allium",
	"minecraft:azure_bluet",
	"minecraft:red_tulip",
	"minecraft:orange_tulip",
	"minecraft:white_tulip",
	"minecraft:lily_of_the_valley",
	"minecraft:firefly_bush",
	"minecraft:wildflowers",
	"minecraft:pink_petals",
	"minecraft:wither_rose",
	"minecraft:open_eyeblossom",
	"minecraft:closed_eyeblossom",
	"minecraft:cactus_flower",
	"minecraft:bamboo_sapling",
	"minecraft:crimson_roots",
	"minecraft:warped_roots",
	"minecraft:twisting_vines",
	"minecraft:large_fern",
	"minecraft:hanging_roots",
	"minecraft:pitcher_plant",
	"minecraft:peony",
	"minecraft:rose_bush",
	"minecraft:lilac",
	"minecraft:moss_carpet",
	"minecraft:sculk_vein",
	"minecraft:seagrass",
	"minecraft:sea_pickle",
	"minecraft:tube_coral",
	"minecraft:brain_coral",
	"minecraft:bubble_coral",
	"minecraft:fire_coral",
	"minecraft:horn_coral",
	"minecraft:dead_tube_coral",
	"minecraft:dead_brain_coral",
	"minecraft:dead_bubble_coral",
	"minecraft:dead_tube_coral_fan",
	"minecraft:dead_brain_coral_fan",
	"minecraft:horn_coral_fan",
	"minecraft:fire_coral_fan",
	"minecraft:bubble_coral_fan",
	"minecraft:brain_coral_fan",
	"minecraft:tube_coral_fan",
	"minecraft:dead_horn_coral",
	"minecraft:dead_fire_coral",
	"minecraft:dead_bubble_coral_fan",
	"minecraft:dead_fire_coral_fan",
	"minecraft:dead_horn_coral_fan",
	"minecraft:pale_hanging_moss",
	"minecraft:weeping_vines",
	"minecraft:dandelion",
	"minecraft:sunflower",
	"minecraft:oxeye_daisy",
	"minecraft:dead_bush",
	"minecraft:poppy",
	"minecraft:cornflower",
	"minecraft:pink_tulip",
	"minecraft:blue_orchid",
	"minecraft:torchflower",
	"minecraft:bamboo",
	"minecraft:vine",
	"minecraft:sugar_cane",
	"minecraft:kelp",
	"minecraft:leaf_litter",
	"minecraft:snow",
	"minecraft:bush",
}
